version: 1.0.{build}
image: Visual Studio 2015
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: nuget restore
build:
  parallel: true
  verbosity: normal
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/f906681f999c65b8726a
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true